In [21]:

# १-डी एरे (1D Array)
a = np.array([1,2,3,4,5,])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [10]:
#day 2
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
#day three 3 6 number items

arr = ([1,2,3,4,5,6])
print(arr)

[1, 2, 3, 4, 5, 6]


In [20]:
#yaslai 2 ota row ra column ma rakhne
kacho_list = ([1,2,3,4,5,6])
arr = np.array(kacho_list)
new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [23]:
#data nikalne katne 
arr = np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [26]:
arr=[0]

In [36]:
#mathmatical operaiton
a = np.array([1,2,3])
b = np.array([10,10,20])
print(a+b)

[11 12 23]


In [37]:
print(a*b)

[10 20 60]


In [30]:
np.sum(a)

np.int64(6)

In [31]:
np.mean(a)

np.float64(2.0)

In [34]:
np.max(a)

np.int64(3)

In [35]:
np.max(b)

np.int64(10)

In [15]:
def greet():
    print("Hello Nabin")
greet()    
    

Hello Nabi


In [16]:
def hello():
    print("I am learning python")
    
    
hello()

I am learning python


In [18]:
def student(name):
    print("Welcome",name)
student("Nabin")
student("Ram")

Welcome Nabin
Welcome Ram


In [20]:
def add(a,b):
    print(a + b)
add(10,12)    
    

22


In [21]:
def name(nam):
    print("Welcome",nam)
name("Nabin")
name("Khanal")

Welcome Nabin
Welcome Khanal


In [22]:
#Homework
def hello():
    print("I am learning python")
hello()    

I am learning python


In [24]:
def student(name):
    print("Welcome:",name)
student("Nabin Khanal")
student("Krishna Khan")

Welcome: Nabin Khanal
Welcome: Krishna Khan


In [26]:
def add (a,b):
    print(a + b)
add(5,89)    


94


In [31]:
def even_odd(num):
    if num % 2 == 0:
        print("Even")
    else:
        print("Odd")
even_odd(30)        
    
    
 

Even


In [34]:
def number(num):
    if num % 2 == 0:
        print("Even")
    else:
        print("Odd")
number(80)        


Even


In [36]:
def rk(k):
    if k % 2 == 0 :
        print("Even")
    else:
        print("Odd")
rk(50)     
rk(3)

Even
Odd
