In [1]:
#Numpay
import numpy as np
numbers = np.array([10,20,30,40])
print(numbers)

[10 20 30 40]


In [3]:
#Math operaion
numbers = np.array([10,20,40])
print(numbers + 5)

[15 25 45]


In [5]:
numbers = np.array([20,34,35,64])
print(np.mean(numbers)) #Mean

38.25


In [6]:
#max 
print(np.max(numbers))

64


In [8]:
#min
print(np.min(numbers))

20


In [10]:
data = np.array([5,10,15,20])
print(data)
print(np.mean(data))

[ 5 10 15 20]
12.5


In [12]:
#Homework
marks = np.array([50,60,70,80])
print(marks)
print(np.max(marks))
print(np.min(marks))
      

[50 60 70 80]
80
50


In [19]:
#Task 2 
num = np.array([20,30,50])
print(num + 10)

#task 3
marks = [60,70,90]
print(np.mean(marks))


[30 40 60]
73.33333333333333


In [17]:
#task 4
ages = np.array([20,21,22,])
print(np.mul(2(ages)))

<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\knabi\AppData\Local\Temp\ipykernel_404\3164290208.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  print(np.mul(2(ages)))


AttributeError: module 'numpy' has no attribute 'mul'