In [1]:
import numpy as np   # 
number = np.array([20,40,39,30])
print(number[0])
print(number[2])

20
39


In [2]:
print(number[-1]) # last array data given us

30


In [3]:
#1 : 4 (Start 1 to befor 4 data output
print(number[1:4])

[40 39 30]


In [5]:
print(number[3])

30


In [6]:
# From index 2 to End
print(number[3])

30


In [7]:
#Practic Task
data = np.array([5,10,15,20])
print(data[1])
print(data[-1])
print(data[1:4])


10
20
[10 15 20]


In [8]:
#homework Task 1
marks = np.array([50,60,70,80,90,100])
print(marks[0])
print(marks[-1])


50
100


In [13]:
# Task 2 Print value from index 1 to 4
nps = np.array([20,30,40,50,60])
print(nps[1:4])


[30 40 50]


In [11]:
# task 3 print first 4 value
workday = np.array([40,50,60,70,90,40])
print(workday[0:4])

[40 50 60 70]


In [15]:
# task 4 print value index 2 to end
players = np.array([30,40,49,50,60])
print(players[2:])

[49 50 60]


In [4]:
pr

NameError: name 'players' is not defined